# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='T ex "Round House 1"', max_length=128)),
                ('desc', models.TextField(help_text='T ex "This is the largest..."')),
                ('min_pers_capacity', models.SmallIntegerField(help_text='Hur många är minsta lämpliga antalet att bo i huset? T ex 1')),
                ('max_pers_capacity', models.IntegerField(help_text='Hur många kan som mest sova i huset? T ex 10')),
                ('n_rooms', models.SmallIntegerField(help_text='Hur många rum har huset?')),
                ('n_doubles', models.SmallIntegerField(help_text='Hur många dubbelsängar?')),
                ('n_singles', models.SmallIntegerField(help_text='Hur många enkelsängar?')),
                ('img_path', models.CharField(help_text='Sökvägen till bilden', max_length=128)),
                ('tripadvisor_book_link', models.URLField(help_text='Länk till tripadvisors bokningssida')),
            ],
        ),
    ]
