# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='max_pers_capacity',
            new_name='pers_capacity',
        ),
        migrations.RemoveField(
            model_name='house',
            name='min_pers_capacity',
        ),
    ]
